# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Observe < Formula
  desc "Self-hosted, single-binary replacement for PostHog + Umami + SigNoz + Sentry"
  homepage "https://github.com/useteploy/teploy-observe"
  version "0.1.6"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.6/observe_0.1.6_darwin_x86_64.tar.gz"
      sha256 "6e32daebe9ecbb552ec90a012c8e6e42b46502e9df4f6234aed35e14ad2ff19f"

      define_method(:install) do
        bin.install "observe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.6/observe_0.1.6_darwin_arm64.tar.gz"
      sha256 "84b7cc9d1996fccda884abd4c3dbd936c76a6c9c3ee1d5042a20b7334b409114"

      define_method(:install) do
        bin.install "observe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.6/observe_0.1.6_linux_x86_64.tar.gz"
      sha256 "8ed66a493c1cb8d14a12fc113b9b6acd0c07de014da271ab819e0c2bc70543e5"
      define_method(:install) do
        bin.install "observe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.6/observe_0.1.6_linux_arm64.tar.gz"
      sha256 "d0ac31f3635c1b8d8ad2d017404431f2db136183c97f0270f4028628eaaac6ad"
      define_method(:install) do
        bin.install "observe"
      end
    end
  end

  test do
    system "#{bin}/observe", "version"
  end
end
