# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Observe < Formula
  desc "Self-hosted, single-binary replacement for PostHog + Umami + SigNoz + Sentry"
  homepage "https://github.com/useteploy/teploy-observe"
  version "0.1.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.0/observe_0.1.0_darwin_x86_64.tar.gz"
      sha256 "a54a6b99cc920894d92d116ce70a67158bb9f2bd93a585abe135e6475f26b5f5"

      def install
        bin.install "observe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.0/observe_0.1.0_darwin_arm64.tar.gz"
      sha256 "a1c323680f27fabe238d39a3cd31467b82bdd4ed039f7be41e1dd830b850e985"

      def install
        bin.install "observe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.0/observe_0.1.0_linux_x86_64.tar.gz"
      sha256 "0ac5c79313e9809948e5ba43bd7dd71e0ea87a2b8c5776911c5899f8aadecd78"

      def install
        bin.install "observe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.0/observe_0.1.0_linux_arm64.tar.gz"
      sha256 "e3dc297e06c8167a9e1f70612632750ecd8722d4cd44061fa3d27c98e355aa0b"

      def install
        bin.install "observe"
      end
    end
  end

  test do
    system "#{bin}/observe", "--version"
  end
end
