# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teploy < Formula
  desc "Zero-downtime Docker deploys to any server via SSH"
  homepage "https://github.com/useteploy/teploy-cli"
  version "0.1.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.22/teploy_darwin_amd64.tar.gz"
      sha256 "70d72f6f59522929a41efc679bbcc26e7408d35b11b48ea84d857bda0bb27134"

      define_method(:install) do
        bin.install "teploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.22/teploy_darwin_arm64.tar.gz"
      sha256 "8547324f2cbd0184afe9947c74d25c00a4ccfecd21506efd749778deaff24c8c"

      define_method(:install) do
        bin.install "teploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.22/teploy_linux_amd64.tar.gz"
      sha256 "65fd27a16384ac138a14aee570dc4b46c91dad019f0de301a3fa261f3ebf2e61"
      define_method(:install) do
        bin.install "teploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.22/teploy_linux_arm64.tar.gz"
      sha256 "4a4e8b81e4ee0afdbf5ecf62994bde1f33ece7c1ab05206e2a9e61e89ad5894a"
      define_method(:install) do
        bin.install "teploy"
      end
    end
  end
end
