# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeployObserve < Formula
  desc "Self-hosted, single-binary replacement for PostHog + Umami + SigNoz + Sentry"
  homepage "https://github.com/useteploy/teploy-observe"
  version "0.1.5"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.5/teploy-observe_0.1.5_darwin_x86_64.tar.gz"
      sha256 "35a6eda1a3bd51424d58217c4d031ed30a18a0a1a8189845a350ac43116677d3"

      define_method(:install) do
        bin.install "teploy-observe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.5/teploy-observe_0.1.5_darwin_arm64.tar.gz"
      sha256 "73d894abea8b6debf3b6a65f8525bd9043976ce55837259dee12987496797b1a"

      define_method(:install) do
        bin.install "teploy-observe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.5/teploy-observe_0.1.5_linux_x86_64.tar.gz"
      sha256 "02820a4dd6a10ccab15e0d67687ea307fd85d804004dc83609292898e73bd9c4"
      define_method(:install) do
        bin.install "teploy-observe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/useteploy/teploy-observe/releases/download/v0.1.5/teploy-observe_0.1.5_linux_arm64.tar.gz"
      sha256 "cd2ac793041d983c1689317b8d2b5d5fd9261866d3edf80cf6a2254cfd3f3a0e"
      define_method(:install) do
        bin.install "teploy-observe"
      end
    end
  end

  test do
    system "#{bin}/teploy-observe", "version"
  end
end
