# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teploy < Formula
  desc "Zero-downtime Docker deploys to any server via SSH"
  homepage "https://github.com/useteploy/teploy-cli"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.11/teploy_darwin_amd64.tar.gz"
      sha256 "d32717e361d89cc23885bcada0bccfccd8ba1a191dce6e8425d7a43230b4c190"

      define_method(:install) do
        bin.install "teploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.11/teploy_darwin_arm64.tar.gz"
      sha256 "3c1bb6b1d522b6a176b5ce35751bcf5b200287cf8cbb3d4b555a6ce99665046a"

      define_method(:install) do
        bin.install "teploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.11/teploy_linux_amd64.tar.gz"
      sha256 "b7aac589b1aba06c9bd2d12c68c54324240bf7b1fadb1ea4eaafda9ab93c134c"
      define_method(:install) do
        bin.install "teploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.11/teploy_linux_arm64.tar.gz"
      sha256 "b8d95e94bee4de95faea4c26d48eb4e001bf85bc1e63c4e491afc0b778c066bf"
      define_method(:install) do
        bin.install "teploy"
      end
    end
  end
end
