# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teploy < Formula
  desc "Zero-downtime Docker deploys to any server via SSH"
  homepage "https://github.com/useteploy/teploy-cli"
  version "0.1.35"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.35/teploy_darwin_amd64.tar.gz"
      sha256 "a9dbc3d2cde3626fb321065b816959e2bda8e517127f2776b498e984b02d0fc2"

      define_method(:install) do
        bin.install "teploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.35/teploy_darwin_arm64.tar.gz"
      sha256 "b663012bd395496c7ba8faee7f97e15a267c3088076dc83ce76727044041e153"

      define_method(:install) do
        bin.install "teploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.35/teploy_linux_amd64.tar.gz"
      sha256 "8f1c190b25e5780b010d523cc1d84e6bfc1d4385446c8fa5eea86ddc14b3d992"
      define_method(:install) do
        bin.install "teploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/useteploy/teploy-cli/releases/download/v0.1.35/teploy_linux_arm64.tar.gz"
      sha256 "5c88978b444c9aeb7cc4b5fafa50135036aefc7fcbc911c8543916aeacf774a3"
      define_method(:install) do
        bin.install "teploy"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/teploy version")
  end
end
