# This file was generated by GoReleaser. DO NOT EDIT.
cask "observe" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "d3336244b647d46220f7bf79e986adbf1a550d5e98b742de69aa1eff0931d821"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d2bcd6986e94e307218c44fda37fd5859cc6f4398656a8f625802f4e72a233a9"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0c0921c174a0e4f8a55ef32bcf634dd210e7c4ddca26876665e0a4e2e9b0347d"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c255b4783178d3c24543df3164a97959b35efce2a5c6dd45a4e6a77fecc472d8"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "observe"
  desc "Self-hosted, single-binary replacement for PostHog + Umami + SigNoz + Sentry"
  homepage "https://github.com/useteploy/teploy-observe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "observe"

  # No zap stanza required

end
