# This file was generated by GoReleaser. DO NOT EDIT.
cask "observe" do
  version "0.1.8"

  on_macos do
    on_intel do
      sha256 "ec6b7747be836971bf207e85a7ad80caedc1caf6c9021eb07adaa122be62717d"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "509f1d2ab7bf4ffcc934e85a32e8f69f120b6b8a37399d0a031eb06df13428b2"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b569fa5a3a1c8ed16a862678a2b19375456989f72a648f6a4fc7d1b726c8de90"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8dc1daed2800b77f52e5833f53837a5cacb2bacf5c1e3715f95aee59a3f3d6e4"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "observe"
  desc "Self-hosted, single-binary replacement for PostHog + Umami + SigNoz + Sentry"
  homepage "https://github.com/useteploy/teploy-observe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "observe"

  # No zap stanza required

end
