# This file was generated by GoReleaser. DO NOT EDIT.
cask "observe" do
  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "07eb1cd034650d8ac115904476e3c9bccd56544393d671f4bbbb644a6583c787"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "81ef4c2dadbfce249613904cb9c88716aaa5a2dc04ec840eb3c1c00746c6eb77"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "229b75b5586e020ed8bb30bf104e166dffdc5a7a774892a24ad3bc5c1dea5cdb"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f4d73d8ff20c1e00a283552e3e7c5f59da3a54416b6b0cef7a5d32037c8eb7f1"
      url "https://github.com/useteploy/teploy-observe/releases/download/v#{version}/observe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "observe"
  desc "Self-hosted, single-binary replacement for PostHog + Umami + SigNoz + Sentry"
  homepage "https://github.com/useteploy/teploy-observe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "observe"

  # No zap stanza required

end
